# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField()),
                ('gas', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dust', models.DecimalField(decimal_places=2, max_digits=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=20)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
